### ISSUE TITLE
Catch invalid key/value store at build time

### ISSUE THREAD

**Issue by kate-goldenring** [fermyon/spin#1232]
Currently, Spin's SQLite key value feature only supports a single `"default"` store per application. The implementation [hard codes only supporting this store](https://github.com/fermyon/spin/blob/665d3a023d2a192b12f32dedec9d89b8fd9f9e7e/crates/trigger/src/lib.rs#L393). Access to this store is granted by the user on the component level in a `Spin.toml`, so to grant my `hello` component access to the store I do the following:
```toml
[[component]]
id = "hello"
source = "target/wasm32-wasi/release/rust_key_value.wasm"
key_value_stores = ["default"]
```

However, currently I can do the following and build and run an application without an error on `spin build --up`. Only when my app tries `Store::open("foo")` during runtime is a `NoSuchStore` error returned. Which as a user may not make sense since I added it to the component:
```
[[component]]
id = "hello"
source = "target/wasm32-wasi/release/rust_key_value.wasm"
key_value_stores = ["default", "foo"]
# OR the following
# key_value_stores = ["foo"]
```

Clear documentation on default store only may suffice, but catching during build time may be better.
