### ISSUE TITLE
Unable to use serde with derive feature.

### ISSUE THREAD

**Issue by RobiFerentz** [fermyon/spin#1309]
I'm attempting to add serde with the derive feature to the "cloud_start" project and I'm getting a conflict error which I'm not sure how to solve.

** My Cargo.toml:
```toml
[package]
name = "cloud_start"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Your first Fermyon Cloud application"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
# Useful crate to handle errors.
anyhow = "1"
# Crate to simplify working with bytes.
bytes = "1"
# General-purpose crate with common HTTP types.
http = "0.2"
serde = { version = "1.0.157", features = [ "derive" ] }
# The Spin SDK.
spin-sdk = { git = "https://github.com/fermyon/spin", tag = "v0.10.1" }
# Crate that generates Rust Wasm bindings from a WebAssembly interface.
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba" }

[workspace]

```

The error I get:
```
error: failed to select a version for `proc-macro2`.
    ... required by package `syn v2.0.0`
    ... which satisfies dependency `syn = "^2.0"` of package `serde_derive v1.0.157`
    ... which satisfies dependency `serde_derive = "=1.0.157"` of package `serde v1.0.157`
    ... which satisfies dependency `serde = "^1.0.52"` (locked to 1.0.157) of package `cloud_start v0.1.0 (/Users/robertferentz/projects/cloud-start)`
versions that meet the requirements `^1.0.52` are: 1.0.52

all possible versions conflict with previously selected packages.

  previously selected package `proc-macro2 v1.0.46`
    ... which satisfies dependency `proc-macro2 = "^1.0"` (locked to 1.0.46) of package `async-trait v0.1.57`
    ... which satisfies dependency `async-trait = "^0.1.51"` (locked to 0.1.57) of package `wit-bindgen-rust v0.2.0 (https://github.com/bytecodealliance/wit-bindgen?rev=cb871cfa1ee460b51eb1d144b175b9aab9c50aba#cb871cfa)`
    ... which satisfies git dependency `wit-bindgen-rust` (locked to 0.2.0) of package `cloud_start v0.1.0 (/Users/robertferentz/projects/cloud-start)`

failed to select a version for `proc-macro2` which could resolve this conflict
```

What can I do to fix this?
