### ISSUE TITLE
`spin watch` configuration handles multi-component applications poorly

### ISSUE THREAD

**Issue by calebschoepp** [fermyon/spin#1402]
Imagine a Spin application that has two components. Here is its `spin.toml`:

```toml
[[component]]
id = "web"
source = "modules/spin_static_fs.wasm"
environment = { FALLBACK_PATH = "index.html" }
# [[component.files]]
# source = "web/dist"
# destination = "/"
[component.trigger]
route = "/..."
[component.build]
workdir = "web"
command = "npm run build"
watch = ["src/**/*.tsx", "src/**/*.css", "package.json"]

[[component]]
id = "api"
source = "api/target/wasm32-wasi/release/api.wasm"
[component.trigger]
route = "/api/..."
[component.build]
workdir = "api"
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

```

Here is its directory structure:

```text
.
├── api
│   ├── Cargo.toml
│   ├── src
│   │   ├── lib.rs
├── modules
│   └── spin_static_fs.wasm
├── spin.toml
└── web
    ├── dist
    │   ├── index.html
    ├── package.json
    ├── src
    │   ├── app
    │   └── components
```

If we run `spin watch` from the root directory it will not properly watch all the files that the user specified in their `component.build.watch`. This is because it takes the globs in that configuration and appends them to the directory the manifest file is in. In practice this means `spin watch` is going to watch `manifest/dir/src/**/*.rs` instead of the correct `manifest/dir/api/src/**/*.rs`.

There are two possible solutions I see:
1. Automatically infer this subdirectory structure from the `component.workdir` configuration.
2. Require users to include this subdirectory structure in their `component.build.watch` configuration e.g. `["api/src/**/*.rs", "api/Cargo.toml"]`

The advantage of 1 is that it is simpler but I'm also worried about scenarios where the assumption of the workdir and subdirectory being the same aren't true.

The advantage of 2 is that it will always work but this comes at the cost of extra overhead for the user. In particular we should update the `spin add` templates to handle configuring the subdirectory for the watch config.

CC @itowlson I'd love to hear your thoughts here.
