### ISSUE TITLE
spin watch not working in WSL when using workdir

### ISSUE THREAD

**Issue by robertohuertasm** [fermyon/spin#1456]
I create an `http-rust` component, run `spin watch` and it works.

If I create an `http-empty` project, then add an `http-rust` component, and run `spin watch`, it doesn't work. This is the `spin.toml` I have.

```toml
spin_manifest_version = "1"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
description = ""
name = "spin-watch-test"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "api"
source = "api/target/wasm32-wasi/release/api.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/api"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api"
watch = ["src/**/*.rs", "Cargo.toml"]
```

I talked to @radu-matei in Discord and send him the full-project, which was a simple hello world. He confirmed it worked in his Mac so everything seems to be pointing to the fact that I'm using WSL2 for development.
