### ISSUE TITLE
Error while deploying to Fermyon Cloud "The key value service is temporarily unavailable"

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#1540]
Hey 👋🏻 

when I try to deploy a Spin application to Fermyon Cloud using `spin deploy`, I receive the following error message:

```text
The key value service is temporarily unavailable.
```

For reference see the actual `spin.toml`:

```toml
spin_manifest_version = "1"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = ""
name = "sample-for-the-issue"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "sample-for-the-issue"
source = "target/wasm32-wasi/release/sample_for_the_issue.wasm"
allowed_http_hosts = ["https://api.foo.com"]
[component.config]
some_config = "some_value"
[component.trigger]
route = "/bar"
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
```

## Subsequent Deployment attempts

When I try to deploy the same app again using `spin deploy`, I receive the following output

```text
Uploading sample-for-the-issue version 0.1.0+r5b15b3b0...
Deploying...
Error: No channel with app_id b65b8241-dade-44b5-a9b9-a5aa47cc5007 and name spin-deploy

Learn more at https://developer.fermyon.com/cloud/faq
```
## Spin CLI Version

I tested with `spin 1.2.1` and `spin 1.1.0`
