### ISSUE TITLE
Modulizing Spin.toml files 

### ISSUE THREAD

**Issue by seungjin** [fermyon/spin#1759]
My spin.toml is getting bigger and bigger (A couple of hundred lines). 
If I can implement some sort of 'include' feature that allows me to modularize spin.toml's content into separate TOML files, 
it would be more organized and productive.

**Comment by seungjin** [comment]
Spin plugin for this?

**Comment by itowlson** [comment]
@seungjin A plugin is an interesting idea.  It could be something the user just remembers to run, or I think @cardoso designed the `spin let` plugin (https://developer.fermyon.com/hub/preview/plugin_spinlet) to allow hooks so possibly it could be configured to automagically combine "includes" on `spin let build` or `spin let up`.  But I'm not sure exactly what hooks spinlet provides.

@fibonacci1729 @michelleN I think you some ideas about this - do you have time to weigh in?

**Comment by fibonacci1729** [comment]
@seungjin I like this idea! I'm curious to hear more about your usecase and how you would like to use such a feature.

Are you thinking something like a new component section key (i.e. `include`) in the `spin.toml` that allows you to modularize components out into their own manifests, for example:

In `spin.toml`:

```toml
spin_manifest_version = "1"
name = "my-app"
version = "0.1.0"
trigger = { type = "http", base = "/" }

[[component]]
include = "path/to/component.toml"
```

Where `path/to/component.toml` looks like:

```toml
id = "my-component"
source = "path/to/wasm"
[trigger]
route = "/..."

# ... other component specific sections ...
```
