### ISSUE TITLE
Component Imports

### ISSUE THREAD

**Issue by fibonacci1729** [fermyon/spin#1779]
For 2.0 (when we officially support preveiw2 components) allow developers to specify how to satisfy component imports in the manifest. E.g.:

```toml
[component.foo.imports]
bar = { path = "bar.wasm" }
```
