### ISSUE TITLE
Allow for more granular route matching in Spin

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#1923]
Currently, the route matching in spin can be of two forms 

```toml
# match a single route
route = "/{path}"

# match any route with the prefix
route = "/{path-prefix}/..."
```
It would be helpful in certain cases if the route matching allowed more granularity. For an example consider the case of a Bartholomew app with a proxy component. 
```toml
[[component]]
id = "bartholomew"
[component.trigger]
route = "/..."

[[component]]
id = "proxy"
[component.trigger]
route = "/spin/*"
```
With such a configuration, the `proxy` component would match the route `/spin/index` but not `/spin/v1/index`.  Thus allowing the `proxy` to handle one specific subset of the routes while `bartholomew` handles the rest. 

There is potential for another level of granularity where we could define something like 
```toml
route = "/spin/*/test"
```
Which would only match `/spin/index/test` but not `/spin/index/something-else`

Thoughts?

**Comment by lann** [comment]
I'm not necessarily opposed to this but just want to note that V2 manifests help with a workaround in some (not all!) situations:

```toml
[[trigger.http]]
route = "/..."
component = "bartholomew"

[[trigger.http]]
route = "/spin/..."
component = "proxy"

[[trigger.http]]
route = "/spin/v1/..."
component = "bartholomew"
```
