### ISSUE TITLE
`spin up` breaks if using with static-fileserver due to asset filename

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#1974]
I wanna host my [Astro](https://astro.build) application in Fermyon Cloud. To do so, I leverage a simple spin application that relies on the `static-fileserver`.

```toml
spin_manifest_version = "1"
authors = ["me"]
description = "foo"
name = "hosting"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
id = "hosting"
files = [{ source = "dist", destination = "/" }]
[component.trigger]
route = "/..."
```

As part of building my application,Astro creates a minified CSS file in the output directory. In my case, the file is called `_...slug_.7d33a135.css`.

When running `spin up`, it breaks with the following error message:

```console
2023-10-27T12:39:39.368811Z ERROR spin_loader::local::assets:
Error copying assets: copy to 
'/private/var/folders/lg/kx2j58hj6mqchgq1zv0gt4tm0000gn/T/spinup-obhMdg/assets/hosting_58b5c9a721e7c0a65b7e478ed904331dbf17def0537358c22210db6533462660/_astro/_.slug_..7d33a135.css' 
outside the application directory

Error: Error copying assets: 1 file(s) not copied
```

To address this issue locally, one could use `spin up --direct-mounts` locally.

I renamed the generated file from `_...slug` to `_.slug` which resolved the issue. 

Ultimately, `spin up` breaks as soon as the filename contains two consecutive dots (`..`).
