### ISSUE TITLE
One trigger and multiple components don't work

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#2130]
* Spin version: `spin 2.1.0-pre0 (87b28483 2023-11-29)`

Given this `spin.toml`, it seems like `spin up` doesn't work:
```toml
spin_manifest_version = 2

[application]
name = "hello-wasi-http"
version = "1.0.0"

[[trigger.http]]
route = "/"
component = "hello"

[component.hello]
source = "main_2023_10_18.component.wasm"
[component.hello.build]
command = """go generate && 
    tinygo build -o main_2023_10_18.wasm -target=wasi main_2023_10_18.go && 
    wasm-tools component embed wit/2023_10_18 main_2023_10_18.wasm > main_2023_10_18.embed.wasm && 
    wasm-tools component new main_2023_10_18.embed.wasm -o main_2023_10_18.component.wasm --adapt wasi_snapshot_preview1.reactor.2023_10_18.wasm
"""

[component.hello2]
source = "main_2023_11_10.component.wasm"
[component.hello2.build]
command = """go generate && 
    tinygo build -o main_2023_11_10.wasm -target=wasi main_2023_11_10.go && 
    wasm-tools component embed wit/2023_11_10 main_2023_11_10.wasm > main_2023_11_10.embed.wasm && 
    wasm-tools component new main_2023_11_10.embed.wasm -o main_2023_11_10.component.wasm --adapt wasi_snapshot_preview1.reactor.2023_11_10.wasm
"""
```

The panic message is 
```bash
thread 'main' panicked at /Users/mossaka/.cargo/git/checkouts/spin-91500438ac5656d2/87b2848/crates/trigger/src/lib.rs:248:88:
called `Option::unwrap()` on a `None` value
```

I think the issue is that the `spin.toml` defines multiple components - "hello" and "hello2" in this case, but only one http trigger for "hello". This messed up the trigger hashmap that looks for all the component IDs. 

I've verified this is a valid spin.toml file by running `spin doctor`

```bash
spin doctor   
📟 The Spin Doctor is in.
🩺 Checking spin.toml...
```

## Expectation

Spin runtime shouldn't panic given a valid spin.toml file.
