### ISSUE TITLE
Mounting the same component on multiple triggers does not work

### ISSUE THREAD

**Issue by karthik2804** [fermyon/spin#2143]
When trying to use the same component for multiple triggers, only the final trigger works when running a `spin up`

An example of a manifest is

```toml
spin_manifest_version = 2

[application]
name = "test"
version = "0.1.0"
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "test"

[[trigger.http]]
route = "/v1/..."
component = "test"

[component.test]
source = "target/wasm32-wasi/release/test.wasm"
allowed_outbound_hosts = []
[component.test.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

```

results in 

```bash
$ spin up        
Logging component stdio to ".spin/logs/"

Serving http://127.0.0.1:3000
Available Routes:
  test: http://127.0.0.1:3000/v1 (wildcard)
```
