### ISSUE TITLE
Configurable allowed outbound hosts based on application variables

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#2153]
I have the following setup: the host I need my application to send outbound connections to is an application variable that is set at runtime through an application variable.

Is there a way to use a (or more) variable(s) to configure an allowed outbound host?

```toml
[variables]
my_host = { default = "http://localhost" }
my_port = { default = "5003" }

[[trigger.http]]
route = "/checkout/..."
component = "checkout"

[component.checkout]
source = "checkout/target/checkout.wasm"
allowed_outbound_hosts = [
	"{{ my_host }}:{{ my_port }}",
]
```
