### ISSUE TITLE
Enable mustache-inspired string templates for `key_value_stores` and others

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#2577]
I'm building a Spin App that consists of multiple components:

```toml
# ...

[component.a]
source = "a/target/wasm32-wasi/release/a.wasm"
key_value_stores = ["data"]

[component.b]
source = "b/target/wasm32-wasi/release/b.wasm"
key_value_stores = ["data"]

# ...
```

Instead of providing the magic string (name of the desired key-value store) **4 times** (twice as part of `key_value_stores` and once per component), I would want to use mustache-inspired string templates as illustrated here:

```toml
#...

[variables]
store = { default = "data" }

[component.a]
source = "a/target/wasm32-wasi/release/a.wasm"
key_value_stores = ["{{ store }}"]

[component.a.variables]
store = "{{ store }}"

[component.b]
source = "b/target/wasm32-wasi/release/b.wasm"
key_value_stores = ["{{ store }}"]

[component.b.variables]
store = "{{ store }}"

# ...
```

**Comment by lann** [comment]
Labels are already a sort of variable in the context of a spin manifest. Could you share more about what you're trying to do here?

**Comment by ThorstenHans** [comment]
What do you mean by `labels`?

What I'm trying to do here:
- Have multiple components that should use the same key-value store
- Prevent myself from having the actual name (magic string) of the key-value store in multiple places

Comparing both variants, no. 1 looks cleaner IMO:

## Variant 1 

```toml
#...

[variables]
store = { default = "data" }

[component.a]
source = "a/target/wasm32-wasi/release/a.wasm"
key_value_stores = ["{{ store }}"]

[component.a.variables]
store = "{{ store }}"

[component.b]
source = "b/target/wasm32-wasi/release/b.wasm"
key_value_stores = ["{{ store }}"]

[component.b.variables]
store = "{{ store }}"

# ...
```

## Variant 2

```toml
#...

[component.a]
source = "a/target/wasm32-wasi/release/a.wasm"
key_value_stores = ["data"]

[component.a.variables]
store = "data"

[component.b]
source = "b/target/wasm32-wasi/release/b.wasm"
key_value_stores = ["data"]

[component.b.variables]
store = "data"

# ...

**Comment by lann** [comment]
## Variant 3

```toml
#...

[component.a]
source = "a/target/wasm32-wasi/release/a.wasm"
key_value_stores = ["store"]

[component.b]
source = "b/target/wasm32-wasi/release/b.wasm"
key_value_stores = ["store"]

# ...
```

It looks like we aren't using the term "label" consistently in documentation, but it is the term for `store` in this example at least internally and in `spin-cloud`.

This label is already a "variable" in the sense that it is a arbitrary user-defined identifier that is shared between the manifest and code.

Actually, I think we want to actively avoid the pattern of making these labels dynamic; the long term goal is to use these labels as component model import names, which need to be static.
