### ISSUE TITLE
Validate component IDs are unique

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#340]
Spin currently permits non-unique IDs, e.g. this loads without complaint:

```toml
[[component]]
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
[component.trigger]
route = "/hello"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
[component.trigger]
route = "/hello"
```

There is currently stuff in the assets code that assumes component IDs are unique - we could fix this, but it might be better to just fail on duplicate ID, (1) because future code might make the same assumption and (2) it would avoid confusion during diagnostics.
