### ISSUE TITLE
Validate HTTP routes are unique

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin#341]
Spin currently permits non-unique HTTP routes, e.g. this loads without complaint:

```toml
[[component]]
id = "hello1"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
[component.trigger]
route = "/hello"

[[component]]
id = "hello2"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
[component.trigger]
route = "/hello"
```

This is overwhelmingly likely to be an error, and should be rejected, or at the very least should receive a trace message at an on-by-default level.

(~We should also document the behaviour of overlapping routes, e.g. `/...` and `/static/...` - I don't think we have that yet, though could be wrong!~  _[ETA: I was, indeed, wrong.]_  It would also be good to error or warn if a route can never be matched.)
