### ISSUE TITLE
Spin SDK

### ISSUE THREAD

**Issue by Mossaka** [fermyon/spin#363]
Related to #362 , I have a minimal working example for using spin-http-engine as a SDK

```rust
fn main() {
    let rt  = Runtime::new().unwrap();
    let engine = Engine::new(Config::default().interruptable(true).cranelift_opt_level(OptLevel::Speed)).unwrap();
    let working_dir_holder = WorkingDirectory::Temporary(tempfile::tempdir().unwrap());
    let working_dir = working_dir_holder.path();
    let file = args().skip(1).next().unwrap();
    let file = PathBuf::from_str(&file).unwrap();
    
    let app = rt.block_on(spin_loader::from_file(file, working_dir)).unwrap();

    let http = rt.block_on(HttpTrigger::new("0.0.0.0:80".to_string(), app, None, None, Some(engine.clone()))).unwrap();
    rt.block_on(http.run()).unwrap();
}
```

with the Cargo.toml looks like
```toml
[package]
name = "spin-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin-http-engine =  { git = "https://github.com/fermyon/spin", branch = "main" }
spin-loader = { git = "https://github.com/fermyon/spin", branch = "main" }
tempfile = "3.3.0"
tokio = { version = "1.11", features = [ "full" ] }
wasmtime = "^0.34"
wasmtime-wasi = "^0.34"
```

One of the benefits of using `spin-http-engine` as a SDK is that we can customize the wasm engine.
