### ISSUE TITLE
Add workdir for component build command

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#406]
ref #352 

The new `spin build` command allows running a build command for each component:

```toml
[component.build]
command = "cargo build --target wasm32-wasi --release --manifest-path http-rust/Cargo.toml"

# implement this
workdir = "some-dir"
```

It would be very helpful to be able to set a working directory to run the build command in.

It feels like the directory should only be accepted if it is relative to the `spin.toml` directory.
