### ISSUE TITLE
Handling dependencies

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#43]
`spin.toml` allows defining a list of dependencies that the main component requires in order to be instantiated:

```toml
    [component.dependencies]
        cache    = { type = "host" }
        markdown = { type = "component", reference = "github/octo-markdown/1.0.0" }
```
However, the behavior of how this section should be used is not currently implemented (or specified).

Proposal: at startup, there should be a step that links the entrypoint module using the components specified in this section, and generates a "linked" component that can be directly instantiated by the execution context (engine).

This section _could_ be potentially generated from `Cargo.toml` in the case of Rust (the format and necessary information is the same).
