### ISSUE TITLE
HTTP router is now non-deterministic

### ISSUE THREAD

**Issue by radu-matei** [fermyon/spin#434]
ref #418 
cc @vdice, @Mossaka 

Consider the following two component Spin application:

```toml
[[component]]
source = "modules/spin_bartholomew.wasm"
id = "bartholomew"
files = [ "content/**/*" , "templates/*", "scripts/*", "config/*"]
[component.trigger]
route = "/..."

[[component]]
source = "modules/spin_static_fs.wasm"
id = "fileserver"
files = [ { source = "static/", destination = "/" } ]
[component.trigger]
route = "/static/..."
```

For overlapping HTTP routes (like in the example above), the HTTP router relies on the order in which they have been defined in `spin.toml`.

Running `spin up` multiple times results in the routes order being non-deterministic:

```
run 1:   spin_http_engine: Constructed router for application fermyon.com: {Exact("/favicon.ico"): "favicon", Wildcard(""): "bartholomew", Wildcard("/static"): "fileserver"}    

run 2:  spin_http_engine: Constructed router for application fermyon.com: {Wildcard("/static"): "fileserver", Wildcard(""): "bartholomew", Exact("/favicon.ico"): "favicon"}    
``` 

The implementation relied on the router being constructed from a `Vec<CoreComponent>` (which had the component order preserved), which changed to a `ComponentMap` (backed by a `HashMap`):

https://github.com/fermyon/spin/pull/418/files#diff-d7033a1fe9a4798b8b561185baca64b8b4fddb02552a9edf0c6ae1162638d6b6R23
