### ISSUE TITLE
config: Decouple component config from trigger/route config

### ISSUE THREAD

**Issue by lann** [fermyon/spin#86]
A component may be used by multiple routes with different configuration (e.g. a fileserver component with different cache config on different paths). Similarly, a single route may reference multiple components (e.g. Middleware #85). To support these configurations, we should decouple the component and route config. An example design might look like:

```toml
name = "my-app"
​
[[component]]
id = "user_ui"
# ...

[[component]]
id = "admin_ui"
​# ...

[[component]]
id = "auth-middleware"
# ...
[component.environment]
session_key = "1234"
​
[[triggers.http]]
path = "/app/..."
component = "user_ui"
interceptors = ["auth"]
​
[[triggers.http]]
path = "/admin/..."
component = "admin_ui"
[[triggers.http.interceptors]]
component = "auth"
environment = { auth_allow_group = ["admins"] }
```
