### ISSUE TITLE
Opinion: Specify workdir on component instead of component build

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#963]
Hey,

with #406 support for specifying the `workdir` for component build (`[component.build]`) was introduced. I wonder if it would make more sense to move the `workdir` property to `[[component]]`...

Moving `workdir` to the component level would allow Spin to re-use it when specifying component `source`

With the current implementation I end up with having the value of `workdir` twice (when sticking to default `cargo build` instructions)

```toml
[[component]]
id = "create-order"
source = "create_order/target/wasm32-wasi/release/create_order.wasm"
[component.trigger]
route = "/..."
[component.build]
workdir = "create_order"
command = "cargo build --target wasm32-wasi --release"
```

Actually, I'm not sure if `component.source` should automatically pick up the `workdir` or not, but it cloud lead to something like this:

```toml
[[component]]
id = "create-order"
workdir = "create_order"
source = "target/wasm32-wasi/release/create_order.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
```
So internally, component source could be computed by combining `workdir` and `source` resulting again in 
`create_order/target/wasm32-wasi/release/create_order.wasm`
