### ISSUE TITLE
allowed_http_hosts should support mustach-inspired syntax to reference varialbes

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#981]
`allowed_http_hosts` (part of component configuration) should allow mustach-inspired syntax to reference global variables. 

Consider the following sample:

```toml
[variables]
slack_root = { default = "hooks.slack.com" }

[[component]]
id = "some"
source = "some.wasm"
allowed_http_hosts = [ "{{ slack_root }}" ]
```
