### ISSUE TITLE
Variable default value ignored and error thrown when Vault Config Provider is used

### ISSUE THREAD

**Issue by ThorstenHans** [fermyon/spin#983]
In my Spin app I've configured three variables (**it's important to have at least one variable configured which is not stored in Vault as secret**)

```toml
[variables]
a = { default = "foo" }
b = { required = true }
c = { required = true }
```
Variable `b` exists as secret in Vault

```bash
vault kv get secret/b
======== Secret Path ========
secret/data/b

======= Metadata =======
Key                Value
---                -----
created_time       2022-12-15T22:11:11.791431757Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1

==== Data ====
Key      Value
---      -----
value    Baz
```

Component configuration is just forwarding the variables:

```toml
[[component]]
id = "some"
source = "some.wasm"
[component.config]
a = "{{ a }}"
b = "{{ b }}"
c = "{{ c }}"
```

When trying to access the configuration data in my component as shown here:

```rust
let a = config::get("a")?;
let b = config::get("b")?;
let c = config::get("c")?;
```
Before starting the Spin app, variable `c` is set as env var.

```bash
export SPIN_APP_C="Baz"
spin build --up --follow-all --runtime-config-file runtime_config.toml
```
When triggering the component, the following error is thrown:

```bash
The Vault server returned an error (status code 404)
2022-12-15T22:25:09.024940Z ERROR rustify::client: error=Server returned error
2022-12-15T22:25:09.024972Z ERROR rustify::endpoint: error=Server returned error
2022-12-15T22:25:09.024982Z ERROR vaultrs::api: Detected errors in API response: []
2022-12-15T22:25:09.024988Z ERROR vaultrs::kv2: error=The Vault server returned an error (status code 404)
```

Although `a` has a default value, I have to provide `a` explicitly by either providing `SPIN_APP_A` as environment variable or by storing `a` in Vault.

The app works as expected **only** if all variables are provided by a **config data provider**.

IMO the `config::get` should not throw when the underlying variable has a default value.
